# Pre-commit hooks for NEDC-BENCH
# See https://pre-commit.com for more information
default_language_version:
  python: python3.10

repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: nedc_eeg_eval/|reference_repos/
      - id: end-of-file-fixer
        exclude: nedc_eeg_eval/|reference_repos/
      - id: check-yaml
        exclude: k8s/.*\.yaml$
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--indent=2"]
        exclude: nedc_eeg_eval/|reference_repos/
      - id: debug-statements
        exclude: nedc_eeg_eval/|reference_repos/
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: nedc_eeg_eval/|reference_repos/

  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        exclude: nedc_eeg_eval/|reference_repos/
      - id: ruff-format
        exclude: nedc_eeg_eval/|reference_repos/

  # MyPy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-toml
          - pydantic
          - numpy
        exclude: nedc_eeg_eval/|reference_repos/|tests/
        args: ["--config-file=pyproject.toml"]

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        exclude: nedc_eeg_eval/|reference_repos/|tests/

  # Markdown formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
        exclude: nedc_eeg_eval/|reference_repos/

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json]
        exclude: nedc_eeg_eval/|reference_repos/

  # Check for secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: nedc_eeg_eval/|reference_repos/

  # Validate GitHub Actions
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [mypy] # MyPy can be slow in CI
