version: "3.8"

services:
  alpha:
    build:
      context: .
      dockerfile: alpha/Dockerfile
    volumes:
      - ./tests:/tests
      - ./output:/output
      - ./nedc_eeg_eval/v6.0.0/data:/data:ro
    environment:
      - NEDC_NFC=/opt/nedc
      - PYTHONPATH=/opt/nedc/lib:/app
    command: pytest /tests -v

  alpha-shell:
    build:
      context: .
      dockerfile: alpha/Dockerfile
    volumes:
      - ./tests:/tests
      - ./output:/output
      - ./nedc_eeg_eval/v6.0.0/data:/data:ro
    environment:
      - NEDC_NFC=/opt/nedc
      - PYTHONPATH=/opt/nedc/lib:/app
    command: /bin/bash
    stdin_open: true
    tty: true
